const mongoose = require("mongoose");

const experienceSchema = new mongoose.Schema(
  {
    host: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    title: { type: String, required: true },
    shortDescription: { type: String, maxlength: 50 },
    description: { type: String },
    category: { type: String },
    price: { type: Number },
    ticketTypes: {
      type: [
        {
          key: { type: String, required: true },
          label: { type: String, required: true },
          price: { type: Number, required: true, min: 0 },
          currency: { type: String, default: "RON" },
          isFree: { type: Boolean, default: false },
          countsTowardCapacity: { type: Boolean, default: true },
          active: { type: Boolean, default: true },
          order: { type: Number, default: 0 },
        },
      ],
      default: [],
    },
    pricingMode: { type: String, enum: ["PER_PERSON", "PER_GROUP"], default: "PER_PERSON" },
    groupPackageSize: { type: Number, default: null },
    durationMinutes: { type: Number },
    currencyCode: { type: String, default: "EUR" },
    activityType: { type: String, enum: ["INDIVIDUAL", "GROUP"], default: "INDIVIDUAL" },
    maxParticipants: { type: Number, default: 1 },
    remainingSpots: { type: Number, default: 1 },
    soldOut: { type: Boolean, default: false },
    status: {
      type: String,
      enum: ["draft", "published", "cancelled", "CANCELLED", "DISABLED", "NO_BOOKINGS", "ARCHIVED"],
      default: "published",
    },
    scheduleType: { type: String, enum: ["ONE_TIME", "LONG_TERM"], default: "ONE_TIME" },
    scheduleGroupId: { type: String, default: null, index: true },
    recurrenceExcludedDates: { type: [String], default: [] },
    environment: { type: String, enum: ["INDOOR", "OUTDOOR", "BOTH"], default: "OUTDOOR" },
    // Schedule (new)
    startsAt: { type: Date, required: true },
    endsAt: { type: Date, required: true },
    // Legacy fields kept for compatibility with existing screens/queries
    date: { type: String },
    startDate: { type: Date },
    endDate: { type: Date },
    startTime: { type: String },
    endTime: { type: String },
    country: { type: String },
    countryCode: { type: String },
    city: { type: String },
    street: { type: String },
    streetNumber: { type: String },
    address: { type: String },
    latitude: { type: Number },
    longitude: { type: Number },
    locationLat: { type: Number },
    locationLng: { type: Number },
    location: {
      formattedAddress: { type: String },
      city: { type: String },
      street: { type: String },
      streetNumber: { type: String },
      postalCode: { type: String },
      country: { type: String },
      lat: { type: Number },
      lng: { type: Number },
    },
    mainImageUrl: { type: String },
    images: [{ type: String }],
    videos: [{ type: String }],
    coverImageUrl: { type: String, default: null },
    coverFocusX: { type: Number, default: 50 },
    coverFocusY: { type: Number, default: 50 },
    mediaRefs: [
      {
        url: { type: String },
        publicId: { type: String },
        resourceType: { type: String, enum: ["image", "video", "raw"], default: "image" },
      },
    ],
    languages: { type: [String], default: [] },
    isActive: { type: Boolean, default: true },
    reminderHostSent: { type: Boolean, default: false },
    mediaCleanedAt: { type: Date },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Experience", experienceSchema);
