const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    displayName: { type: String },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    role: {
      type: String,
      enum: ["EXPLORER", "HOST", "ADMIN", "BOTH"],
      default: "EXPLORER",
    },
    isHost: { type: Boolean, default: false },
    hostProfile: {
      displayName: String,
      bio: String,
      languages: { type: [String], default: [] },
      city: String,
      country: String,
      phone: String,
      avatar: String,
    },
    display_name: { type: String },
    age: { type: Number },
    city: { type: String },
    country: { type: String },
    languages: { type: [String], default: [] },
    about_me: { type: String },
    shortBio: { type: String },
    profilePhoto: { type: String },
    avatar: { type: String },
    phoneVerified: { type: Boolean, default: false },
    emailVerified: { type: Boolean, default: false },
    emailVerificationCode: { type: String },
    emailVerificationExpires: { type: Date },
    emailVerificationAttempts: { type: Number, default: 0 },
    experience: { type: String },
    total_participants: { type: Number, default: 0 },
    total_events: { type: Number, default: 0 },
    stripeAccountId: { type: String },
    isStripeChargesEnabled: { type: Boolean, default: false },
    isStripePayoutsEnabled: { type: Boolean, default: false },
    isStripeDetailsSubmitted: { type: Boolean, default: false },
    isTrustedParticipant: { type: Boolean, default: false },
    clientFaultCancelsCount: { type: Number, default: 0 },
    phone: { type: String },
    phoneCountryCode: { type: String },
    resetPasswordToken: { type: String },
    resetPasswordExpires: { type: Date },
    resetOtpCode: { type: String },
    resetOtpExpires: { type: Date },
    resetOtpAttempts: { type: Number, default: 0 },
    deleteOtpCode: { type: String },
    deleteOtpExpires: { type: Date },
    deleteOtpAttempts: { type: Number, default: 0 },
    tokenVersion: { type: Number, default: 0 },
    lastAuthAt: { type: Date },
    rating_avg: { type: Number, default: 0 },
    rating_count: { type: Number, default: 0 },
    isBanned: { type: Boolean, default: false },
    isBlocked: { type: Boolean, default: false },
    expoPushToken: { type: String },
    expoPushTokens: { type: [String], default: [] },
    termsAccepted: { type: Boolean, default: false },
    termsAcceptedAt: { type: Date },
    termsVersion: { type: String },
    favorites: [{ type: mongoose.Schema.Types.ObjectId, ref: "Experience" }],
  },
  { timestamps: true }
);

module.exports = mongoose.model("User", userSchema);
